---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: statscontainer
  namespace: egs9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stats
  template:
    metadata:
      labels:
        app: stats
    spec:
      containers:
      - name: stats
        image: registry.deti:5000/egs9/stats:1632
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8003
---
apiVersion: v1
kind: Service
metadata:
  name: stats-service
  namespace: egs9
spec:
  ports:
  - port: 80
    targetPort: 8003
  selector:
    app: stats

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stats-ingress
  namespace: egs9
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  rules:
  - host: moviestats.k3s
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: stats-service
            port:
              number: 80